@host=http://localhost:5024

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Amichai",
    "lastName": "mantinband",
    "email": "amichai@mantinband.com",
    "password": "Amiko1232"
}
